runtime: nodejs20 

env: flex

handlers:
  - url: /.*
    script: auto

env_variables:
  NODE_ENV: "production"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_num_instances: 1
  max_num_instances: 5
