services:
  backend:
    container_name: backend
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      - DATABASE=mongodb://admin:adminpassword@mongo:27017/wdc?authSource=admin
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - D:/mongo_data:/data/db

    
    